export const mockImportLicenses = [
  'Mozilla Public License 2.0',
  'Apache License 2.0',
  'Eclipse Public License 1.0',
  'MIT License',
  'GNU General Public License v1.0 or later',
  'GNU General Public License v2.0 or later',
  'GNU General Public License v3.0 or later',
  'GNU Lesser General Public License v2.1 or later',
  'GNU General Public License v2.0 only',
  'Python 3.0a1 License',
  'Unspecified',
  'NuGet-based Microsoft Package Manager License',
  'Nunit License',
  'Common Public License 1.0',
  'OpenSSL Combined License',
  'Python Software Foundation License 2.3',
  'Mozilla Public License 1.1',
  'European Union Public License 1.1',
  'Microsoft Public License',
  'GNU Affero General Public License v3.0',
  'Vim License',
  'pgAdmin License',
  'Python License 2.0',
  'VirtualBox Exception to GPL 2.0 only',
  'Apache License 1.1',
  'Common Development and Distribution License 1.0',
  'Open Symphony 1.1 License',
  'Erlang Public License v1.1',
  'GNU General Public License v3.0 only',
  'Mozilla Public License 1.0',
  'Artistic License 1.0',
  'GNU Lesser General Public License v2.1 only',
  'Vim Charityware License v 5.3',
  'Public Domain',
  'MySQL GPL FOSS License Exception v 4.1',
  'Code Project Open License',
  'Shared Source Permissive License (SS-PL)',
  'Reciprocal Public License 1.5',
  'Microsoft ASP.NET Universal Providers EULA',
  'Bind License',
  'GPL 3.0 with Classpath Exception',
  'Ruby License',
  'Microsoft .NET Framework 1.1 License',
  'Common Public Attribution License 1.0',
  'curl License',
  'GNU Library General Public License v2 or later',
  'BSD One Clause License',
  'Xmlproc License',
  'PostgreSQL License',
  'Affero General Public License v1.0',
  'Pyinstaller GPL 2.0 with exception License',
  'Artistic License 2.0',
  'IBM developerWorks International License Agreement for Non-Warrented Programs',
  'GNU Lesser General Public License v3.0 or later',
  'Oracle SQL Developer License',
  'Do What The F*ck You Want To Public License',
  'Rpart License',
  'Zope Public License 2.1',
  'BSD 2-clause NetBSD License',
  'Jdom License',
  'ISC License',
  'Paint.NET License',
  'Microsoft Reciprocal License',
  'Sleepycat License',
  'GNU Affero General Public License v3.0 only',
];
