import {
  DeploymentType,
  OutputFormatType,
  PackageManager,
  Project,
  ProjectDevelopmentType,
  ProjectStatusType,
} from '../../models';

export const ProjectSeed: Array<Partial<Project>> = [
  {
    name: 'go-licenses',
    gitUrl: 'https://github.com/google/go-licenses',
    packageManager: { code: 'golang-modules' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-insecure-go',
    gitUrl: 'https://github.com/vsurge/hello-insecure-go',
    packageManager: { code: 'golang-modules' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'barista-web',
    gitUrl: 'https://github.com/Optum/barista',
    customPackageManagerPath: 'barista-web/',
    packageManager: { code: 'npm' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'barista-api',
    gitUrl: 'https://github.com/Optum/barista',
    customPackageManagerPath: 'barista-api/',
    packageManager: { code: 'npm' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'barista-scan',
    gitUrl: 'https://github.com/Optum/barista',
    customPackageManagerPath: 'barista-scan/',
    packageManager: { code: 'npm' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'python-getting-started-3.7.5',
    gitUrl: 'https://github.com/vsurge/python-getting-started',
    packageManager: { code: 'python3-pip' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'python-getting-started-2.7.17',
    gitUrl: 'https://github.com/vsurge/python-getting-started',
    packageManager: { code: 'python2_7-pip' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'Atom',
    gitUrl: 'https://github.com/atom/atom',
    packageManager: { code: 'npm' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    outputFormat: { code: 'json' } as OutputFormatType,
    developmentType: { code: 'community' } as ProjectDevelopmentType,
  },
  {
    name: 'WebGoat',
    gitUrl: 'https://github.com/WebGoat/WebGoat',
    packageManager: { code: 'maven' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    outputFormat: { code: 'json' } as OutputFormatType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'nest-bull',
    gitUrl: 'https://github.com/fwoelffel/nest-bull',
    packageManager: { code: 'npm' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-insecure-maven',
    gitUrl: 'https://github.com/vsurge/hello-insecure-maven',
    packageManager: { code: 'maven' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-insecure-maven-nested',
    gitUrl: 'https://github.com/vsurge/hello-insecure-maven-nested',
    customPackageManagerPath: 'project/',
    customPackageManagerFilename: 'another-pom.xml',
    packageManager: { code: 'maven' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-insecure-archive',
    pathToUploadFileForScanning: 'https://github.com/vsurge/hello-insecure/raw/master/hello-insecure-archive.zip',
    customPackageManagerPath: 'hello-insecure-archive/',
    packageManager: { code: 'npm' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'distributed' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-insecure',
    gitUrl: 'https://github.com/vsurge/hello-insecure',
    packageManager: { code: 'npm' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'distributed' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-insecure-bitbucket',
    gitUrl: 'https://austin1@bitbucket.org/austin1/hello-insecure.git',
    packageManager: { code: 'npm' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'distributed' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-insecure-npm-nested',
    gitUrl: 'https://github.com/vsurge/hello-insecure-npm-nested',
    customPackageManagerPath: 'project/',
    packageManager: { code: 'npm' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'distributed' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-secure-node',
    gitUrl: 'https://github.com/vsurge/hello-secure-node',
    packageManager: { code: 'npm' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'distributed' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-insecure-dotnet',
    gitUrl: 'https://github.com/vsurge/hello-insecure-dotnet',
    packageManager: { code: 'nuget' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-insecure-nuget-nested',
    gitUrl: 'https://github.com/vsurge/hello-insecure-nuget-nested',
    customPackageManagerPath: 'project/',
    customPackageManagerFilename: 'HelloInsecure.sln',
    packageManager: { code: 'nuget' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'hello-shallow-nuget',
    gitUrl: 'https://github.com/vsurge/hello-shallow-nuget',
    packageManager: { code: 'nuget' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'distributed' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'OWASP',
    gitUrl: 'https://github.com/jeremylong/DependencyCheck',
    packageManager: { code: 'none' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'ZeroCode',
    gitUrl: 'https://github.com/authorjapps/zerocode',
    packageManager: { code: 'none' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'GraphQL for .NET',
    gitUrl: 'https://github.com/graphql-dotnet/graphql-dotnet',
    customPackageManagerPath: 'src/',
    packageManager: { code: 'nuget' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
  },
  {
    name: 'GraphQL for .NET For Demo User',
    gitUrl: 'https://github.com/graphql-dotnet/graphql-dotnet',
    customPackageManagerPath: 'src/',
    packageManager: { code: 'nuget' } as PackageManager,
    projectStatus: { code: 'new' } as ProjectStatusType,
    outputFormat: { code: 'json' } as OutputFormatType,
    deploymentType: { code: 'unspecified' } as DeploymentType,
    developmentType: { code: 'organization' } as ProjectDevelopmentType,
    userId: 'user-id',
  },
];
