/**
 * Barista API
 * REST API documentation for the Barista system
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ProjectScanStatusType } from './project-scan-status-type';
import { Project } from './project';


export interface BomSecurityException { 
    createdAt: object;
    id: number;
    metaData: object;
    tag: string;
    updatedAt: object;
    notes: string;
    userId: string;
    cveId: string;
    project: Project;
    projectScanStatus: ProjectScanStatusType;
    securityItemPath: string;
}

