/**
 * Barista API
 * REST API documentation for the Barista system
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface ClearlyDefined {
  createdAt: object;
  id: number;
  metaData: object;
  tag: string;
  updatedAt: object;
  copyrights: string;
  indentifier: string;
  license: string;
  licensetext: string;
  name: string;
  uuid: string;
  version: string;
  website: string;
}

