/**
 * Barista API
 * REST API documentation for the Barista system
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { License } from './license';


export interface Obligation { 
    createdAt: object;
    id: number;
    metaData: object;
    tag: string;
    updatedAt: object;
    code: string;
    desc: string;
    licenses: Array<License>;
    name: string;
}

