/**
 * Barista API
 * REST API documentation for the Barista system
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BomSecurityException } from './bom-security-exception';
import { PackageManager } from './package-manager';
import { ProjectStatusType } from './project-status-type';
import { ProjectDevelopmentType } from './project-development-type';
import { BomManualLicense } from './bom-manual-license';
import { ProjectNote } from './project-note';
import { Scan } from './scan';
import { DeploymentType } from './deployment-type';
import { BomLicenseException } from './bom-license-exception';
import { OutputFormatType } from './output-format-type';


export interface Project { 
    createdAt: object;
    id: number;
    metaData: object;
    tag: string;
    updatedAt: object;
    askID: string;
    configuration: string;
    currentVersion: string;
    customPackageManagerFilename: string;
    customPackageManagerPath: string;
    deploymentType: DeploymentType;
    description: string;
    developmentType: ProjectDevelopmentType;
    gitUrl: string;
    globalLicenseException: boolean;
    globalSecurityException: boolean;
    importMetaData: object;
    licenseExceptions: Array<BomLicenseException>;
    manualLicenses: Array<BomManualLicense>;
    name: string;
    outputEmail: string;
    outputFormat: OutputFormatType;
    owner: string;
    packageManager: PackageManager;
    pathToUploadFileForScanning: string;
    projectNotes: Array<ProjectNote>;
    projectStatus: ProjectStatusType;
    scans: Array<Scan>;
    securityExceptions: Array<BomSecurityException>;
    userId: string;
    wasImported: boolean;
}

