/**
 * Barista API
 * REST API documentation for the Barista system
 *
 * The version of the OpenAPI document: 1.0
 *
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ClearlyDefined } from './clearly-defined';


export interface ProjectDistinctLicenseAttributionDto {
    packageName: string;
    publisherName: object;
    publisherUrl: object;
    license: object;
    licenselink: object;
    clearDefined: ClearlyDefined;
}

