/**
 * Barista API
 * REST API documentation for the Barista system
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Project } from './project';
import { JobInfoDto } from './job-info-dto';
import { LicenseScanResult } from './license-scan-result';
import { SecurityScanResult } from './security-scan-result';


export interface Scan { 
    createdAt: object;
    id: number;
    metaData: object;
    tag: string;
    updatedAt: object;
    completedAt: object;
    jobInfo: JobInfoDto;
    licenseScanResults: Array<LicenseScanResult>;
    project: Project;
    securityScanResults: Array<SecurityScanResult>;
    startedAt: object;
}

