/**
 * Barista API
 * REST API documentation for the Barista system
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface SystemConfiguration { 
    code: string;
    createdAt: object;
    description: string;
    isDefault: boolean;
    metaData: object;
    sortOrder: number;
    updatedAt: object;
    aboutMenu: object;
    aboutPageContent: string;
    contactMenu: object;
    githubComPasswordEnvVar: string;
    githubComUsernameEnvVar: string;
    githubEnterprisePasswordEnvVar: string;
    githubEnterpriseUrlEnvVar: string;
    githubEnterpriseUsernameEnvVar: string;
    helpMenu: object;
    maxProcesses: number;
    npmCacheDirectory: string;
    npmRegistry: string;
    spdxLicenseListVersion: string;
    askIdDisplayName: string;
    profileMenu: object;
}

