/**
 * Barista API
 * REST API documentation for the Barista system
 *
 * The version of the OpenAPI document: 1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UserInfo { 
    displayName: string;
    email: string;
    groups: Array<string>;
    id: string;
    role: UserInfo.RoleEnum;
    userName: string;
}
export namespace UserInfo {
    export type RoleEnum = 'Admin' | 'Collaborator' | 'LicenseAdmin' | 'SecurityAdmin';
    export const RoleEnum = {
        Admin: 'Admin' as RoleEnum,
        Collaborator: 'Collaborator' as RoleEnum,
        LicenseAdmin: 'LicenseAdmin' as RoleEnum,
        SecurityAdmin: 'SecurityAdmin' as RoleEnum
    };
}


